name: pr-add-label

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR number
        id: pr_number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Run Custom Action
        uses: thinkasany/pr-label-action@dev
        with:
          github_token: ${{ secrets.DOOCS_BOT_ACTION_TOKEN }}
          pr_number: ${{ env.PR_NUMBER }}
          organize_name: "doocs"
          team_name: "leetcode-algorithm"
